---
title: "Bayesian Priors"
author: "Anthony Davidson"
date: "5 April 2019"
output: html_document
---


**Overall priors**

"Non-informative prior distributions were selected to allow the data to drive parameter estimation [@gelman2006]. The prior distributions of capture histories were assigned binomial distributions and variance terms were assigned broad uniform prior (0-100) as suggested by @gelman2006. The remaining parameters were assigned normally distributed prior with mean 0 and variance 0.00001. Each model was run for 100 000 iterations with a burn-in of 50 000 iterations, which was sufficient to achieve convergence as judged by visual inspection of the chain histories."

Why and how....



\newline

**Software**

Models were fitted in a Bayesian framework using Markov Chain Monte Carlo (MCMC) methods and implemented in JAGS, called from R v.4.3.4  using the jagsUI package. Each coefficient was modelled with uninformative priors for each season and valley. We specified non-informative priors to allow the data to drive parameter estimation.  Each model was run for 100000 iterations with a burn-in of 50000 iterations, which was sufficient to achieve convergence as judged by visual inspection of the chain histories . For a full model description see Appendix 1.